apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshops

resources:
- namespace.yaml

bases:
- https://github.com/openshift-homeroom/workshop-homeroom?ref=develop

configMapGenerator:
- name: homeroom-configs
  behavior: merge
  files:
  - workshops.yaml
