apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshops

resources:
- namespace.yaml

bases:
- https://github.com/openshift-homeroom/workshop-homeroom?ref=develop

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: homeroom
  path: ingress.yaml

configMapGenerator:
- name: homeroom-configs
  behavior: merge
  files:
  - workshops.yaml
