apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/openshift-homeroom/workshop-spawner/resources/overlays/hosted-workshop?ref=develop

namePrefix: lab-gs-javascript-

commonLabels:
  app: lab-gs-javascript

configMapGenerator:
- name: spawner-environ
  behavior: merge
  env: settings.txt

patches:
- oauthclient.yaml
- ingress.yaml
