apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-browser-testing

resources:
- namespace.yaml

bases:
- https://github.com/openshift-homeroom/lab-browser-testing/.workshop?ref=1.1

configMapGenerator:
- name: spawner-environ
  behavior: merge
  env: settings.txt
