apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-k8s-fundamentals

resources:
- namespace.yaml

bases:
- https://github.com/openshift-labs/lab-k8s-fundamentals/.workshop?ref=master

configMapGenerator:
- name: spawner-environ
  behavior: merge
  env: settings.txt
